[alembic]
script_location = alembic
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql+asyncpg://elarion_user:elarion_pass@localhost:5432/elarion
