"""Progress parity against the pre-M6 service on isolated relational fixtures."""
import uuid
from types import SimpleNamespace
from unittest.mock import AsyncMock
import pytest
from sqlalchemy import select, func, insert, update, delete
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Session
from tests.unit.test_dashboard_read import data, seed, Database, UID, OTHER, NOW
from app.modules.module2_content.models import Course, CourseModule, Lesson
from app.modules.module4_experience.models import StudentProgress, LearningPathState, PathState, Enrollment
from app.modules.module5_assessment.models import Test as Assessment, Submission
from app.modules.module4_experience.services import progress_service as service
from app.modules.module4_experience import router
from app.shared.exceptions import AuthorizationError, LessonLockedError
CID=uuid.UUID(int=100)
LID=uuid.UUID(int=1000)

async def legacy_progress(
    db: AsyncSession,
    student_id: uuid.UUID,
    course_id: uuid.UUID,
) -> dict:
    """
    Calculate course completion percentage for a student.

    Returns: {
        total_lessons: int,
        completed_lessons: int,
        percentage: float (0.0 to 100.0),
        locked_lessons: int
    }
    """
    from app.modules.module2_content.models import CourseModule, Lesson, LessonStatus
    from app.modules.module5_assessment.models import Test, Submission, SubmissionStatus
    from sqlalchemy.orm import selectinload

    # Count total published lessons in course
    total_result = await db.execute(
        select(func.count(Lesson.id))
        .join(CourseModule, Lesson.module_id == CourseModule.id)
        .where(
            CourseModule.course_id == course_id,
            Lesson.status == LessonStatus.published,
        )
    )
    total = total_result.scalar_one()

    if total == 0:
        return {"total_lessons": 0, "completed_lessons": 0, "percentage": 0.0, "locked_lessons": 0}

    # Count completed lessons
    completed_result = await db.execute(
        select(func.count(StudentProgress.id))
        .join(Lesson, StudentProgress.lesson_id == Lesson.id)
        .join(CourseModule, Lesson.module_id == CourseModule.id)
        .where(
            StudentProgress.student_id == student_id,
            CourseModule.course_id == course_id,
            StudentProgress.completed == True,
            Lesson.status == LessonStatus.published,
        )
    )
    completed = completed_result.scalar_one()

    # Count locked lessons
    locked_result = await db.execute(
        select(func.count(LearningPathState.id))
        .join(Lesson, LearningPathState.lesson_id == Lesson.id)
        .join(CourseModule, Lesson.module_id == CourseModule.id)
        .where(
            LearningPathState.student_id == student_id,
            CourseModule.course_id == course_id,
            LearningPathState.state == PathState.locked,
        )
    )
    locked = locked_result.scalar_one()

    percentage = round((completed / total) * 100, 1) if total > 0 else 0.0

    # A newer final generated by staff must not hide this student's saved result.
    submission = (await db.execute(
        select(Submission).join(Test, Submission.test_id == Test.id)
        .where(Test.course_id == course_id, Test.is_focused_retest == False,
               Submission.student_id == student_id)
        .order_by(Submission.submitted_at.desc(), Submission.id.desc()).limit(1)
    )).scalar_one_or_none()
    latest_submission_id = submission.id if submission else None
    assessment_status = ("completed" if submission.status == SubmissionStatus.graded else "in_progress") if submission else "not_started"

    return {
        "total_lessons": total,
        "completed_lessons": completed,
        "percentage": percentage,
        "locked_lessons": locked,
        "assessment_status": assessment_status,
        "latest_submission_id": latest_submission_id,
    }

@pytest.mark.asyncio
@pytest.mark.parametrize('scenario', ['baseline','empty','unpublished_only','not_started','completed','draft_locked','false_completion','other_student','other_course','focused_retest','new_final_without_submission','tie','graded','pending','missing','draft_course','archived_course','inactive_enrollment'])
async def test_exact_old_new_contract(data, scenario):
    engine,sql=data;seed(engine,2)
    with engine.begin() as conn:
        if scenario=='empty':conn.execute(delete(Lesson).where(Lesson.module_id==uuid.UUID(int=200)))
        if scenario=='unpublished_only':conn.execute(update(Lesson).where(Lesson.module_id==uuid.UUID(int=200)).values(status='draft'))
        if scenario=='not_started':
            conn.execute(delete(StudentProgress));conn.execute(delete(Submission))
        if scenario=='completed':
            for j in (1,2):conn.execute(insert(StudentProgress),dict(student_id=UID,lesson_id=uuid.UUID(int=1000+j),completed=True))
        if scenario=='draft_locked':conn.execute(insert(LearningPathState),dict(student_id=UID,lesson_id=uuid.UUID(int=1003),state='locked'))
        if scenario=='false_completion':conn.execute(update(StudentProgress).values(completed=False))
        if scenario=='other_student':
            conn.execute(insert(StudentProgress),dict(student_id=OTHER,lesson_id=uuid.UUID(int=1002),completed=True))
            conn.execute(insert(LearningPathState),dict(student_id=OTHER,lesson_id=LID,state='locked'))
            conn.execute(insert(Submission),dict(id=uuid.UUID(int=9999),test_id=uuid.UUID(int=300),student_id=OTHER,status='graded',submitted_at=NOW.replace(year=2027)))
        if scenario=='other_course':conn.execute(update(Submission).where(Submission.test_id==uuid.UUID(int=301)).values(submitted_at=NOW.replace(year=2028)))
        if scenario=='focused_retest':
            conn.execute(insert(Assessment),dict(id=uuid.UUID(int=900),course_id=CID,title='Retest',is_focused_retest=True))
            conn.execute(insert(Submission),dict(id=uuid.UUID(int=901),test_id=uuid.UUID(int=900),student_id=UID,status='graded',submitted_at=NOW.replace(year=2027)))
        if scenario=='new_final_without_submission':conn.execute(insert(Assessment),dict(id=uuid.UUID(int=900),course_id=CID,title='New final'))
        if scenario=='tie':
            conn.execute(update(Submission).where(Submission.test_id==uuid.UUID(int=300)).values(submitted_at=NOW))
        if scenario in ('graded','pending'):conn.execute(update(Submission).where(Submission.id==uuid.UUID(int=500)).values(status=scenario))
        if scenario in ('draft_course','archived_course'):conn.execute(update(Course).where(Course.id==CID).values(status=scenario.split('_')[0]))
        if scenario=='inactive_enrollment':conn.execute(update(Enrollment).values(status='inactive'))
    target=uuid.UUID(int=99999) if scenario=='missing' else CID
    for uid in (UID,OTHER):
        with Session(engine) as session:old=await legacy_progress(Database(session),uid,target)
        sql.clear()
        with Session(engine) as session:new=await service.get_course_progress(Database(session),uid,target)
        assert new==old and len(sql)==1
        assert all(term not in sql[0] for term in ('body_markdown','content_assets','submissions.answers','overall_score','users','lesson_skills'))
        if scenario=='draft_locked' and uid==UID:assert new['locked_lessons']==2
        if scenario in ('empty','unpublished_only','missing'):assert set(new)=={'total_lessons','completed_lessons','percentage','locked_lessons'}
        if scenario=='completed' and uid==UID:assert new['percentage']==100
        if scenario in ('focused_retest','new_final_without_submission','other_student','tie') and uid==UID:assert new['latest_submission_id']==uuid.UUID(int=500)

@pytest.mark.asyncio
@pytest.mark.parametrize('size',[1,30,300])
async def test_query_count_independent_of_course_size(data,size):
    engine,sql=data;seed(engine,1)
    with engine.begin() as conn:
        conn.execute(delete(Lesson))
        for j in range(size):
            lid=uuid.UUID(int=10000+j)
            conn.execute(insert(Lesson),dict(id=lid,module_id=uuid.UUID(int=200),title='Bounded',slug=str(lid),sequence_order=j,status='published',body_markdown='Do not load'))
            conn.execute(insert(StudentProgress),dict(student_id=UID,lesson_id=lid,completed=j%2==0))
            conn.execute(insert(LearningPathState),dict(student_id=UID,lesson_id=lid,state='locked' if j%3==0 else 'mastered'))
    with Session(engine) as session:old=await legacy_progress(Database(session),UID,CID)
    sql.clear()
    with Session(engine) as session:new=await service.get_course_progress(Database(session),UID,CID)
    assert new==old and new['total_lessons']==size and len(sql)==1

@pytest.mark.asyncio
async def test_completion_and_lock_changes_are_fresh(data,monkeypatch):
    engine,_=data;seed(engine,1)
    monkeypatch.setattr('app.modules.module4_experience.services.dashboard_service.invalidate_dashboard_cache',AsyncMock())
    with Session(engine) as session:
        db=Database(session);before=await service.get_course_progress(db,UID,CID)
        await service.mark_lesson_complete(db,UID,uuid.UUID(int=1002),15)
        after=await service.get_course_progress(db,UID,CID)
        assert before['completed_lessons']==1 and after['completed_lessons']==2 and after['percentage']==66.7
        assert after['locked_lessons']==before['locked_lessons']==1
    with engine.begin() as conn:conn.execute(update(LearningPathState).values(state='unlocked'))
    with Session(engine) as session:assert (await service.get_course_progress(Database(session),UID,CID))['locked_lessons']==0

@pytest.mark.asyncio
@pytest.mark.parametrize('role',['Instructor','Admin'])
async def test_nonstudent_endpoint_denied_before_query(data,role):
    engine,sql=data;sql.clear()
    user=SimpleNamespace(id=UID,has_role=lambda r:r==role)
    with Session(engine) as session:
        with pytest.raises(AuthorizationError):await router.get_course_progress(CID,user,Database(session))
    assert sql==[]

@pytest.mark.asyncio
async def test_lock_authority_unchanged_even_after_completion(data):
    engine,_=data;seed(engine,1)
    with engine.begin() as conn:conn.execute(insert(StudentProgress),dict(student_id=UID,lesson_id=uuid.UUID(int=1001),completed=True))
    user=SimpleNamespace(id=UID,has_role=lambda r:r=='Student')
    with Session(engine) as session:
        db=Database(session);stats=await service.get_course_progress(db,UID,CID)
        assert stats['completed_lessons']==2 and stats['locked_lessons']==1
        with pytest.raises(LessonLockedError):await service.check_lesson_access(db,uuid.UUID(int=1001),user)
