import {
  AppWindowIcon,
  AppleIcon,
  BirdIcon,
  BoneIcon,
  BrainIcon,
  CodeIcon,
  CornerUpRightIcon,
  CpuIcon,
  DropletsIcon,
  FishIcon,
  FlowerIcon,
  FootprintsIcon,
  GlobeIcon,
  HeartIcon,
  KeyboardIcon,
  LaptopIcon,
  LeafIcon,
  MonitorIcon,
  MoonIcon,
  MountainIcon,
  MousePointerIcon,
  MoveUpIcon,
  RabbitIcon,
  RepeatIcon,
  ServerIcon,
  ShieldCheckIcon,
  SnowflakeIcon,
  SproutIcon,
  SunIcon,
  TreePineIcon,
  UtensilsIcon,
  WavesIcon,
  WifiIcon,
  WindIcon,
  type LucideIcon } from
'lucide-react';
import type { IconKey } from '@/types/student/learning';

export const flowIcons: Record<IconKey, LucideIcon> = {
  sun: SunIcon,
  water: DropletsIcon,
  air: WindIcon,
  leaf: LeafIcon,
  sprout: SproutIcon,
  rabbit: RabbitIcon,
  bird: BirdIcon,
  fish: FishIcon,
  snowflake: SnowflakeIcon,
  tree: TreePineIcon,
  flower: FlowerIcon,
  heart: HeartIcon,
  brain: BrainIcon,
  bone: BoneIcon,
  food: UtensilsIcon,
  apple: AppleIcon,
  moon: MoonIcon,
  run: FootprintsIcon,
  keyboard: KeyboardIcon,
  cpu: CpuIcon,
  monitor: MonitorIcon,
  wifi: WifiIcon,
  globe: GlobeIcon,
  server: ServerIcon,
  laptop: LaptopIcon,
  code: CodeIcon,
  repeat: RepeatIcon,
  forward: MoveUpIcon,
  turn: CornerUpRightIcon,
  mouse: MousePointerIcon,
  app: AppWindowIcon,
  shield: ShieldCheckIcon,
  mountain: MountainIcon,
  waves: WavesIcon
};