"""Add object keys

Revision ID: 15fc1715d468
Revises: 656d8e9f05c2
Create Date: 2026-10-03 05:55:38.550841

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15fc1715d468'
down_revision: Union[str, None] = '656d8e9f05c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('thumbnail_object_key', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('video_object_key', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('thumbnail_object_key', sa.Text(), nullable=True))
    op.add_column('video_generation_jobs', sa.Column('video_object_key', sa.Text(), nullable=True))
    op.add_column('video_generation_jobs', sa.Column('thumbnail_object_key', sa.Text(), nullable=True))
    op.add_column('session_attendances', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('session_attendances', sa.Column('attendance_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_attendances', 'attendance_verified')
    op.drop_column('session_attendances', 'duration_seconds')
    op.drop_column('video_generation_jobs', 'thumbnail_object_key')
    op.drop_column('video_generation_jobs', 'video_object_key')
    op.drop_column('lessons', 'thumbnail_object_key')
    op.drop_column('lessons', 'video_object_key')
    op.drop_column('courses', 'thumbnail_object_key')
    # ### end Alembic commands ###
