"""Add VideoGenerationJob

Revision ID: d48b1116c808
Revises: 856dc43cb128
Create Date: 2026-10-02 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd48b1116c808'
down_revision = '856dc43cb128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE video_job_status AS ENUM ('queued', 'planning', 'scripting', 'audio_generating', 'assets_preparing', 'rendering', 'uploading', 'ready', 'failed')")
    op.create_table('video_generation_jobs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('submission_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('weakness_flag_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('skill_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('remediation_plan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', postgresql.ENUM('queued', 'planning', 'scripting', 'audio_generating', 'assets_preparing', 'rendering', 'uploading', 'ready', 'failed', name='video_job_status', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('script_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scene_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_manifest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_manifest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_taxonomy.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weakness_flag_id'], ['weakness_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_generation_jobs_status', 'video_generation_jobs', ['status'], unique=False)
    op.create_index('ix_video_generation_jobs_student_id', 'video_generation_jobs', ['student_id'], unique=False)
    op.create_index('ix_video_generation_jobs_weakness_flag_id', 'video_generation_jobs', ['weakness_flag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_generation_jobs_weakness_flag_id', table_name='video_generation_jobs')
    op.drop_index('ix_video_generation_jobs_student_id', table_name='video_generation_jobs')
    op.drop_index('ix_video_generation_jobs_status', table_name='video_generation_jobs')
    op.drop_table('video_generation_jobs')
    op.execute("DROP TYPE video_job_status")
    # ### end Alembic commands ###
